name: CI

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:

jobs:
  test:
    name: Unit and UI Tests
    runs-on: macOS-latest
    steps:
    - uses: actions/setup-go@v2
      with:
        go-version: 1.18
    - uses: actions/checkout@v2
    - name: Set up config files
      run: |
        cp IVPNClient/Config/staging.template.xcconfig IVPNClient/Config/staging.xcconfig
        cp IVPNClient/Config/release.template.xcconfig IVPNClient/Config/release.xcconfig
        cp IVPNClient/Config/OpenVPNConf.template.swift IVPNClient/Config/OpenVPNConf.swift
        cp fastlane/Appfile.template fastlane/Appfile
    - name: Build and test
      run: xcodebuild test -scheme IVPNClient -destination 'platform=iOS Simulator,name=iPhone 14'
